<?php

namespace Afpa\Bundle\SpotifyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * artistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class artistRepository extends EntityRepository
{
}
